
# to test:
# docker run --rm -it --name seaweedfs_test --net seaweedfs_internal --cap-add SYS_ADMIN --device=/dev/fuse:/dev/fuse --security-opt=apparmor:unconfined --entrypoint sh chrislusf/seaweedfs:1.41
# / # apk --no-cache add fuse
# / # weed mount -filer=filer:8888 -dir=/mnt -filer.path=/
# then docker exec into that container, as fuse will be running in the foreground...
# docker exec -it seaweedfs_test sh
# / # cd /mnt
# /mnt # cp -r /var .
# /mnt # du 
# and then do the same from the other swarm nodes...

version: "3.6"

services:
  master:
    hostname: "{{.Node.Hostname}}_{{.Service.Name}}"
    image: chrislusf/seaweedfs:latest
    command: "master -ip 0.0.0.0 -port 9333 -defaultReplication=000"
    networks:
      - internal
    # volumes:
    #   - data:/data
    deploy:
      replicas: 1

  volume:
    hostname: "{{.Node.Hostname}}_{{.Service.Name}}"
    image: chrislusf/seaweedfs:latest
    command: 'volume -max=15 -mserver=master:9333 -port=8080'
    networks:
      - internal
    volumes:
      - data:/data
    deploy:
      mode: global

  filer:
    hostname: "{{.Node.Hostname}}_{{.Service.Name}}"
    image: chrislusf/seaweedfs:latest
    command: 'filer -master=master:9333'
    networks:
      - internal
    # volumes:
    #   - data:/data
    deploy:
      mode: global

  # TODO: figure out how to handle a swarm where the number of managers has been reduced...
  # this is a --force-new-cluster event, so probably just needs disaster recovery docs

  # docker run --network seaweedfs_internal appcelerator/etcd etcdctl --endpoints=etcd:2379 put /test once
  # docker run --network seaweedfs_internal appcelerator/etcd etcdctl --endpoints=etcd:2379 get / --prefix
  etcd:
    hostname: "{{.Node.Hostname}}_{{.Service.Name}}"
    image: appcelerator/etcd:latest
    volumes:
      - etcd:/data
    networks:
      - internal
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 1
    deploy:
      mode: global
      placement:
        constraints:
         - node.role == manager

  s3:
    image: chrislusf/seaweedfs:latest
    # ports:
    # - 8333:8333
    command: 's3 -filer=filer:8888'
    networks:
      - internal
    # volumes:
    #   - data:/data

  # docker-volume-plugin-run-once:
  #   image: docker:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: "docker plugin install --alias swarm:develop --grant-all-permissions svendowideit/seaweedfs-volume-plugin:develop DEBUG=true"
  #   deploy:
  #     mode: global
  #     restart_policy:
  #       condition: none
  docker-volume-plugin:
    image: svendowideit/seaweedfs-volume-plugin-rootfs:develop
    environment:
      DEBUG: 'true'
    volumes:
      - /var/lib/docker/plugins/swarm/rootfs/tmp:/tmp
      - /var/lib/docker/plugins/swarm/rootfs/mnt:/mnt
      - /var/lib/docker/plugins/swarm/propagated-mount:/propagated-mount
      - /run:/run
    networks:
      - internal
    deploy:
      mode: global
      restart_policy:
        condition: none

volumes:
  data:
  etcd:

networks:
  internal:
    attachable: true
